# Generated by Django 6.0.6 on 2026-07-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SigninInfo',
            fields=[
                ('uname', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32, unique=True)),
                ('mobile', models.BigIntegerField(max_length=12)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'signin_info',
            },
        ),
    ]
