# Generated by Django 6.0.6 on 2026-07-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=32)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
