# Generated by Django 6.0.6 on 2026-07-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
