# Generated by Django 6.0.6 on 2026-07-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIfo',
            fields=[
                ('fname', models.CharField(max_length=32)),
                ('lname', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32, unique=True)),
                ('mobile', models.BigIntegerField(max_length=12, unique=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=12)),
                ('semester', models.IntegerField()),
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'studentinfo',
            },
        ),
    ]
