# Generated by Django 6.0.6 on 2026-07-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentifo',
            name='mobile',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='studentifo',
            name='semester',
            field=models.CharField(max_length=32),
        ),
    ]
