# Generated by Django 6.0.6 on 2026-07-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0002_alter_studentifo_mobile_alter_studentifo_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigninInfo',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.BigIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'signin_info',
            },
        ),
    ]
