# Generated by Django 6.0.6 on 2026-07-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0003_signininfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signininfo',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
