# Generated by Django 5.2 on 2026-07-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediCart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('price', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('mfg_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
    ]
