# Generated by Django 6.0.6 on 2026-07-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
            ],
            options={
                'db_table': 'customer_info',
            },
        ),
    ]
