# Generated by Django 6.0.6 on 2026-07-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=50, unique=True)),
                ('salary', models.FloatField()),
            ],
            options={
                'db_table': 'user_info_1',
            },
        ),
    ]
