# Generated by Django 6.0.6 on 2026-07-24 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='UserInformation',
        ),
        migrations.AlterModelTable(
            name='userinformation',
            table='UserInformation',
        ),
    ]
