# Generated by Django 6.0.6 on 2026-07-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_rename_userinfo_userinformation_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinformation',
            table='customer_info',
        ),
    ]
