# Generated by Django 6.0.6 on 2026-08-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_info',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('seller_name', models.CharField(max_length=100)),
                ('discount_percent', models.IntegerField()),
                ('rating', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product1',
            },
        ),
    ]
