# Generated by Django 6.0.6 on 2026-08-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('department', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('joiningDate', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Employee_info',
            },
        ),
    ]
